name: maven

on:
  pull_request:
    branches:
      - main
      - snapshot-*
    paths-ignore:
      - '.github/workflows/release.yml'
      - 'README.md'

jobs:
  package:
    uses: dbstar-org/general/.github/workflows/maven-package.yml@v1
  verify:
    needs: package
    uses: dbstar-org/general/.github/workflows/maven-verify.yml@v1
  sonar:
    needs: verify
    uses: dbstar-org/general/.github/workflows/maven-sonar.yml@v1
    secrets: inherit