name: Package with Maven

on:
  workflow_call:
    inputs:
      MAVEN_OPTS:
        description: 'Parameters used to start up the JVM running Maven.'
        default: ${{ vars.MAVEN_OPTS }}
        required: false
        type: string

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: dbstar-org/setup-maven@v1
      - name: Package with Maven
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MAVEN_OPTS: ${{ inputs.MAVEN_OPTS }}
        run: mvn clean package -DskipTests=true
