name: Verify with Maven

on:
  workflow_call:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: dbstar-org/setup-maven@v1
      - name: Verify with Maven
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn -B -U clean verify
