name: Package with Maven

on:
  workflow_call:

env:
  package-env: abc

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: dbstar-org/setup-maven@v1
      - name: Package with Maven
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn -B -U clean package -DskipTests=true
      - run: env
