name: maven

on:
  workflow_call:
    inputs:
      MAVEN_OPTS:
        description: 'Parameters used to start up the JVM running Maven.'
        default: ${{ vars.MAVEN_OPTS }}
        required: false
        type: string
    secrets:
      SONAR_PROJECT_KEY:
        required: false
      SONAR_TOKEN:
        required: false
      SONAR_HOST_URL:
        required: false
      GPG_PRIVATE_KEY:
        required: false
      GPG_PASSPHRASE:
        required: false

permissions:
  packages: read

jobs:
  package:
    uses: ./.github/workflows/maven-package.yml
    with:
      MAVEN_OPTS: ${{ inputs.MAVEN_OPTS }}
  verify:
    needs: package
    uses: ./.github/workflows/maven-verify.yml
    with:
      MAVEN_OPTS: ${{ inputs.MAVEN_OPTS }}
  sonar:
    needs: verify
    uses: ./.github/workflows/maven-sonar.yml
    with:
      MAVEN_OPTS: ${{ inputs.MAVEN_OPTS }}
    secrets:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  deploy:
    needs: sonar
    if: github.ref_type == 'branch' && (github.ref_name == 'main' || startsWith(github.ref_name, 'snapshot-'))
    permissions:
      packages: write
    uses: ./.github/workflows/maven-deploy.yml
    with:
      MAVEN_OPTS: ${{ inputs.MAVEN_OPTS }}
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}