name: Verify with Maven to SonarQube

on:
  workflow_call:
    inputs:
      MAVEN_OPTS:
        description: 'Parameters used to start up the JVM running Maven.'
        default: ${{ vars.MAVEN_OPTS }}
        required: false
        type: string
    secrets:
      SONAR_PROJECT_KEY:
        required: false
      SONAR_TOKEN:
        required: false
      SONAR_HOST_URL:
        required: false

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Parameter
        id: verify
        env:
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          CONTINUE=true
          if [ -z "$SONAR_PROJECT_KEY" ]; then
            echo "::notice title=Verify with Maven to SonarQube::add secrets.SONAR_PROJECT_KEY to launch" && CONTINUE=false
          else
            [ -z "$SONAR_TOKEN" ] && echo "::warning title=Verify with Maven to SonarQube::need secrets.SONAR_TOKEN" && CONTINUE=false
            [ -z "$SONAR_HOST_URL" ] && echo "::warning title=Verify with Maven to SonarQube::need secrets.SONAR_HOST_URL" && CONTINUE=false
          fi
          echo "continue=$CONTINUE" >> $GITHUB_OUTPUT
      - name: Setup Maven
        id: setup-maven
        if: steps.verify.outputs.continue == 'true'
        uses: dbstar-org/setup-maven@v1
        with:
          java-version: 11
          fetch-depth: 0
          cache-strategy: 'restore'
      - name: Cache SonarQube packages
        if: steps.verify.outputs.continue == 'true'
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
      - name: Verify with Maven to SonarQube
        if: steps.verify.outputs.continue == 'true'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          MAVEN_OPTS: ${{ inputs.MAVEN_OPTS }}
        run: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.8.0.2131:sonar -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
      - name: Update Maven Repository Cache
        if: steps.verify.outputs.continue == 'true'
        uses: dbstar-org/maven-cache-updater@v1
        with:
          cache-matched-key: ${{ steps.setup-maven.outputs.cache-matched-key }}
