name: Release with Maven

on:
  workflow_call:
    inputs:
      MAVEN_OPTS:
        description: 'Parameters used to start up the JVM running Maven.'
        default: ${{ vars.MAVEN_OPTS }}
        required: false
        type: string
    secrets:
      GPG_PRIVATE_KEY:
        required: false
      GPG_PASSPHRASE:
        required: false
      GIT_USER_EMAIL:
        required: false
      OSS_USERNAME:
        required: false
      OSS_PASSWORD:
        required: false

jobs:
  release:
    if: github.ref_type == 'branch' && (github.ref_name == 'main' || startsWith(github.ref_name, 'snapshot-'))
    runs-on: ubuntu-latest
    steps:
      - name: Verify Parameter
        id: verify
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          CONTINUE=true
          [ -z "$GPG_PRIVATE_KEY" ] && echo "::warning title=Release with Maven::need secrets.GPG_PRIVATE_KEY" && CONTINUE=false
          [ -z "$GPG_PASSPHRASE" ] && echo "::warning title=Release with Maven::need secrets.GPG_PASSPHRASE" && CONTINUE=false
          [ -z "$GIT_USER_EMAIL" ] && echo "::warning title=Release with Maven::need secrets.GIT_USER_EMAIL" && CONTINUE=false
          echo "continue=$CONTINUE" >> $GITHUB_OUTPUT
      - name: Verify Ossrh Parameter
        id: verify-ossrh
        if: steps.verify.outputs.continue == 'true'
        env:
          OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
          OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
        run: |
          CONTINUE=true
          [ -z "$OSS_USERNAME" ] && echo "::notice title=Release to Ossrh::add secrets.OSS_USERNAME to launch" && CONTINUE=false
          [ -z "$OSS_PASSWORD" ] && echo "::notice title=Release to Ossrh::add secrets.OSS_PASSWORD to launch" && CONTINUE=false
          echo "continue=$CONTINUE" >> $GITHUB_OUTPUT
      - name: Setup Maven
        if: steps.verify.outputs.continue == 'true'
        uses: dbstar-org/setup-maven@v1
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Configure Git user
        if: steps.verify.outputs.continue == 'true'
        run: |
          git config --local user.name ${{ github.actor }}
          git config --local user.email ${{ secrets.GIT_USER_EMAIL }}
          git config --local commit.gpgsign true

      - name: Prepare Release
        if: steps.verify.outputs.continue == 'true'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_OPTS: ${{ inputs.MAVEN_OPTS }}
        run: mvn release:prepare -Prelease,distribution-github -DsignTag=true

      - name: Backup Release Properties
        if: steps.verify.outputs.continue == 'true' && steps.verify-ossrh.outputs.continue == 'true'
        run: cp ${{ github.workspace }}/release.properties ${{ github.workspace }}/release.properties.bak

      - name: Perform Release to Github
        if: steps.verify.outputs.continue == 'true'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_OPTS: ${{ inputs.MAVEN_OPTS }}
        run: mvn release:perform -Prelease,distribution-github

      - name: Restore Release Properties from Backup
        if: steps.verify.outputs.continue == 'true' && steps.verify-ossrh.outputs.continue == 'true'
        run: mv ${{ github.workspace }}/release.properties.bak ${{ github.workspace }}/release.properties

      - name: Perform Release to Ossrh
        if: steps.verify.outputs.continue == 'true' && steps.verify-ossrh.outputs.continue == 'true'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
          OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
          MAVEN_OPTS: ${{ inputs.MAVEN_OPTS }}
        run: mvn release:perform -Prelease,distribution-ossrh
