name: Verify with Maven to SonarQube

on:
  workflow_call:
    inputs:
      project-key:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true

jobs:
  sonar:
    if: inputs.project-key != ''
    runs-on: ubuntu-latest
    steps:
      - uses: dbstar-org/setup-maven@v1
        with:
          java-version: 11
          fetch-depth: 0
      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
      - name: Check Parameter secrets.SONAR_TOKEN
        continue-on-error: true
        if: env.SONAR_TOKEN == ''
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: echo 'need secrets.SONAR_TOKEN' && exit 1
      - name: Check Parameter secrets.SONAR_HOST_URL
        continue-on-error: true
        if: env.SONAR_HOST_URL == ''
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: echo 'need secrets.SONAR_HOST_URL' && exit 1
      - name: Verify with Maven to SonarQube
        if: env.SONAR_TOKEN != '' && env.SONAR_HOST_URL != ''
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B -U verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ inputs.project-key }}
