name: Verify with Maven

on:
  workflow_call:
    inputs:
      MAVEN_OPTS:
        description: 'Parameters used to start up the JVM running Maven.'
        default: ${{ vars.MAVEN_OPTS }}
        required: false
        type: string

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven
        id: setup-maven
        uses: dbstar-org/setup-maven@v1
        with:
          cache-strategy: 'restore'
      - name: Verify with Maven
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MAVEN_OPTS: ${{ inputs.MAVEN_OPTS }}
        run: mvn clean verify
      - name: Update Maven Repository Cache
        uses: dbstar-org/maven-cache-updater@v1
        with:
          cache-matched-key: ${{ steps.setup-maven.outputs.cache-matched-key }}
