name: Verify with Maven to SonarQube

on:
  workflow_call:
    inputs:
      SONAR_PROJECT_KEY:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Notice
        if: inputs.SONAR_PROJECT_KEY == ''
        run: echo "::notice title=SonarQube::add vars.SONAR_PROJECT_KEY to launch Verify with Maven to SonarQube"
      - name: Setup Maven
        if: inputs.SONAR_PROJECT_KEY != ''
        uses: dbstar-org/setup-maven@v1
        with:
          java-version: 11
          fetch-depth: 0
      - name: Cache SonarQube packages
        if: inputs.SONAR_PROJECT_KEY != ''
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
      - name: Verify with Maven to SonarQube
        if: inputs.SONAR_PROJECT_KEY != ''
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          [ -z "$SONAR_TOKEN" ] && echo "::warning title=SonarQube::need secrets.SONAR_TOKEN" && CONTINUE='stop'
          [ -z "$SONAR_HOST_URL" ] && echo "::warning title=SonarQube::need secrets.SONAR_HOST_URL" && CONTINUE='stop'
          [ -z "$CONTINUE" ] || exit 0 
          mvn -B -U verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ inputs.SONAR_PROJECT_KEY }}
