name: Deploy to Github

on:
  workflow_call:
    secrets:
      GPG_PRIVATE_KEY:
        required: true
      GPG_PASSPHRASE:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: dbstar-org/setup-maven@v1
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Deploy to Github
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: mvn -B -U clean deploy -P release,distribution-github
